# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
weather_df = pd.read_csv("../WeatherPy/output_data/weather.csv")
weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,East London,-33.02,27.91,71.60,88,96,9.17,ZA,1603465033
1,Jamestown,42.10,-79.24,66.00,82,1,8.05,US,1603464793
2,Constitución,-35.33,-72.42,60.35,61,0,10.00,CL,1603465034
3,Pangnirtung,66.15,-65.71,26.60,92,90,3.36,CA,1603465034
4,Butaritari,3.07,172.79,82.33,70,87,12.41,KI,1603465034

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Store latitude and longitude in locations
locations = weather_df[["Lat", "Lng"]]
weight = weather_df["Humidity"]

In [5]:
# Heatmap
figure = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add and display
figure.add_layer(heat_layer)
figure

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
# Max temperature lower than 80 degrees but higher than 70. 
# Wind speed less than 10 mph. 
# Zero cloudiness.

format_cities = weather_df.dropna()

weather_fitted = format_cities.loc[(format_cities['Cloudiness'] > 0) & (format_cities['Wind Speed'] < 10)] 
weather_fitted_df = weather_fitted.loc[(weather_fitted['Max Temp'] > 70) & (weather_fitted['Max Temp'] <= 80)]
weather_fitted_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,East London,-33.02,27.91,71.60,88,96,9.17,ZA,1603465033
16,Hilo,19.73,-155.09,71.60,78,40,4.70,US,1603464776
18,Rikitea,-23.12,-134.97,73.80,78,47,2.21,PF,1603464833
27,Avera,33.19,-82.53,75.20,83,1,8.05,US,1603465038
49,Hermanus,-34.42,19.23,75.99,68,17,5.01,ZA,1603464756
...,...,...,...,...,...,...,...,...,...
513,Svay Rieng,11.09,105.80,78.49,83,100,4.47,KH,1603465112
519,Buluang,13.31,123.34,79.20,87,97,0.29,PH,1603465139
522,Beni,0.50,29.47,71.17,99,100,0.69,CD,1603465139
536,Acajutla,13.59,-89.83,78.01,100,40,3.02,SV,1603464863
542,Kloulklubed,7.04,134.26,77.00,94,75,8.08,PW,1603465145

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure